/**
 * HostPMS Integration - TypeScript Types
 * Defines interfaces for HostPMS API and internal data structures
 */

// ==================== HostPMS API Types ====================

/**
 * HostPMS OAuth Token Response
 */
export interface HostPMSOAuthToken {
  access_token: string;
  token_type: 'Bearer';
  expires_in: number; // seconds
  created_at?: number; // timestamp when token was created
}

/**
 * HostPMS Guest (Portuguese field names)
 */
export interface HostPMSGuest {
  name: string;
  email?: string;
  phone?: string;
  country?: string;
  nif?: string; // Portuguese tax ID
  address?: string;
  city?: string;
  postal_code?: string;
}

/**
 * HostPMS Room
 */
export interface HostPMSRoom {
  type: string; // e.g., "Quarto Duplo", "Suite"
  number: string;
  floor?: number;
}

/**
 * HostPMS Dates
 */
export interface HostPMSDates {
  check_in: string; // ISO date string
  check_out: string; // ISO date string
  created_at: string; // ISO datetime string
  updated_at?: string;
}

/**
 * HostPMS Pricing
 */
export interface HostPMSPricing {
  total: number;
  currency: string; // 'EUR'
  rate_plan: string; // e.g., "Flexível", "Não Reembolsável"
  iva?: number; // Portuguese VAT
  taxa_turistica?: number; // Tourist tax
  discount?: number;
}

/**
 * HostPMS Reservation (from API)
 */
export interface HostPMSReservation {
  reservation_id: string;
  property_id: string;
  guest: HostPMSGuest;
  room: HostPMSRoom;
  dates: HostPMSDates;
  pricing: HostPMSPricing;
  status: HostPMSReservationStatus;
  channel: HostPMSChannel;
  payment_method?: HostPMSPaymentMethod;
  special_requests?: string;
  number_of_guests?: number;
  source_url?: string;
}

/**
 * HostPMS Reservation Status (Portuguese)
 */
export type HostPMSReservationStatus =
  | 'confirmado'    // confirmed
  | 'cancelado'     // cancelled
  | 'check_in'      // checked in
  | 'check_out'     // checked out
  | 'no_show'       // no show
  | 'pendente';     // pending

/**
 * HostPMS Channel (Portuguese)
 */
export type HostPMSChannel =
  | 'direto'        // direct
  | 'booking_com'   // Booking.com OTA
  | 'expedia'       // Expedia OTA
  | 'airbnb'        // Airbnb OTA
  | 'agencia'       // travel agent
  | 'outro';        // other

/**
 * HostPMS Payment Method (Portuguese)
 */
export type HostPMSPaymentMethod =
  | 'credit_card'   // cartão de crédito
  | 'debit_card'    // cartão de débito
  | 'cash'          // dinheiro
  | 'bank_transfer' // transferência bancária
  | 'mb_way';       // MB Way (Portuguese payment app)

/**
 * HostPMS API Reservations List Response
 */
export interface HostPMSReservationsResponse {
  reservations: HostPMSReservation[];
  total: number;
  page: number;
  limit: number;
  has_more: boolean;
}

/**
 * HostPMS Webhook Event
 */
export interface HostPMSWebhookEvent {
  event: HostPMSEventType;
  timestamp: string; // ISO datetime
  property_id: string;
  data: HostPMSReservation | HostPMSPayment | any;
}

/**
 * HostPMS Event Types
 */
export type HostPMSEventType =
  | 'reservation.created'
  | 'reservation.updated'
  | 'reservation.cancelled'
  | 'reservation.check_in'
  | 'reservation.check_out'
  | 'reservation.no_show'
  | 'payment.received'
  | 'guest.created'
  | 'room.status_changed';

/**
 * HostPMS Payment
 */
export interface HostPMSPayment {
  payment_id: string;
  reservation_id: string;
  amount: number;
  currency: string;
  method: HostPMSPaymentMethod;
  status: 'pending' | 'completed' | 'failed';
  timestamp: string;
}

// ==================== Internal/Unified Types ====================

/**
 * Unified Booking (our standardized schema)
 */
export interface UnifiedBooking {
  // IDs
  id: string; // UUID generated by us
  external_id: string; // HostPMS reservation_id
  source: 'hostpms';
  hotel_id: string; // property_id

  // Guest info
  guest_name: string;
  guest_email?: string;
  guest_phone?: string;
  guest_country?: string;

  // Room info
  room_number: string;
  room_type: string; // Mapped to English

  // Dates
  check_in_date: Date;
  check_out_date: Date;
  booked_at: Date;

  // Pricing
  total_amount: number;
  currency: string;

  // Status & Channel (mapped to English)
  status: UnifiedBookingStatus;
  channel: UnifiedChannel;
  payment_method?: string;

  // ML features
  lead_time: number; // days between booking and check-in
  length_of_stay: number; // nights

  // Metadata
  synced_at: Date;
  version: number;
  raw_data?: any; // Optional: store original HostPMS payload
}

/**
 * Unified Booking Status (English)
 */
export type UnifiedBookingStatus =
  | 'confirmed'
  | 'cancelled'
  | 'checked_in'
  | 'checked_out'
  | 'no_show'
  | 'pending';

/**
 * Unified Channel (English)
 */
export type UnifiedChannel =
  | 'direct'
  | 'ota'
  | 'agent'
  | 'walk_in'
  | 'other';

// ==================== Integration Configuration ====================

/**
 * HostPMS Integration Config
 */
export interface HostPMSConfig {
  property_id: string;
  client_id: string;
  client_secret: string;
  webhook_secret: string;
  api_base_url: string;
  enabled: boolean;
  sync_frequency: 'realtime' | 'hourly' | 'daily';
  language: 'pt-PT' | 'es-ES' | 'en-US';
}

/**
 * HostPMS Client Options
 */
export interface HostPMSClientOptions {
  property_id: string;
  client_id: string;
  client_secret: string;
  base_url?: string;
  timeout?: number;
  retry_attempts?: number;
}

/**
 * Sync Metadata
 */
export interface SyncMetadata {
  integration_id: string;
  property_id: string;
  last_sync_at?: Date;
  last_success_at?: Date;
  last_error_at?: Date;
  last_error?: string;
  total_synced: number;
  total_errors: number;
}

/**
 * Webhook Verification Result
 */
export interface WebhookVerificationResult {
  valid: boolean;
  error?: string;
  age_seconds?: number;
}

/**
 * API Error Response
 */
export interface HostPMSAPIError {
  error: string;
  message: string;
  status_code: number;
  details?: any;
}

/**
 * Sync Result
 */
export interface SyncResult {
  success: boolean;
  records_processed: number;
  records_saved: number;
  records_failed: number;
  duration_ms: number;
  errors: string[];
}
